[project]
name = "livellm-browser"
version = "2.0.1"
description = "Browser in docker with VNC and Chrome, exposing CDP over a launcher API"
readme = "README.md"
requires-python = "==3.9.*"
dependencies = [
    "fastapi>=0.121.3",
    "pydantic>=2.12.4",
    "uvicorn>=0.38.0",
    "patchright==1.56.0",
]
