services:
  livellm-browser:
    build:
      context: ./browser
      dockerfile: Dockerfile
    image: kamasalyamov/livellm-browser:2.0.1
    container_name: livellm-browser-2.0.1
    ports:
      # VNC port
      - "5901:5901"
      # noVNC web interface
      - "6901:6901"
      # FastAPI Launcher
      - "9000:9000"
    environment:
      - VNC_PW=headless
      - VNC_RESOLUTION=1920x1080
      - DISPLAY=:1
    volumes:
      # Mount profiles directory from host with read/write access
      - profiles_volume:/home/headless/Desktop/app/profiles:rw
    restart: unless-stopped
    stop_grace_period: 10s
    shm_size: '4gb'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '4gb'
        reservations:
          cpus: '0.5'
          memory: '2gb'

  livellm-controller:
    build:
      context: ./controller
      dockerfile: Dockerfile
    image: kamasalyamov/livellm-controller:2.0.1
    container_name: livellm-controller-2.0.1
    ports:
      # FastAPI Controller
      - "8000:8000"
    environment:
      - LAUNCHER_URL=http://livellm-browser:9000
      - LAUNCHER_HOST=livellm-browser
    depends_on:
      - livellm-browser
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2gb'

volumes:
  profiles_volume:
    driver: local
